<?php



/**
 * Implements hook_menu()
 */

function blogsummary_menu(){
	$items['user/%user/blog'] = array(
		'title' => 'Posts',
		'page callback' => 'blogsummary_get_posts',
		'access callback' => TRUE,
		'type' => MENU_LOCAL_TASK,
		'weight' => 0,
	);
	$items['admin/config/people/blogsummary'] = array(
		'title' => 'Blog Summary',
		'description' => 'list of Recent Blog Posts',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('blogsummary_config_form'),
		'access arguments' => array('administer users'),
		'type' => MENU_NORMAL_ITEM,
	);
	$items['accountblog'] = array(
		'title' => 'Posts',
		'page callback' => 'blogsummary_accountdashboard_view',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		'weight' => 0,
		'menu_name' => 'accountdashboard',
	);
	return $items;
}

function blogsummary_accountdashboard_view(){
	return blogsummary_get_posts();
}

/**
 *  
 */
function blogsummary_config_form($form, &$form_state){
	$form['blogsummary_number_posts'] = array(
		'#type' => 'textfield',
		'#title' => t('Number of Posts'),
		'#default_value' => variable_get('blogsummary_number_posts','5'),
		'#size' => 20,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form;
}

function blogsummary_config_form_submit($form, &$form_state){
	variable_set('blogsummary_number_posts',$form_state['values']['blogsummary_number_posts']);
	drupal_set_message(t('The settings have been saved'));
}
/**
 * Get the Recent 5 Posts 
 *
 * @param: $number
 * 		An optional number which specify the number of posts to show on the dashboard page
 * @return
 *      A renderable array containing the posts
 */
function blogsummary_get_posts(){
	$number = variable_get('blogsummary_number_posts',5);
	$query = db_select('node','n');
	$u_alias = $query->innerJoin('users','u','%alias.uid=n.uid');
	$query->addField($u_alias, 'name', 'username');
	$result = $query
		->fields('n',array('nid', 'title','created'))
		->condition("{$u_alias}.name", 'dustsnow')
		->condition('type', 'blog')
		->condition('n.status', 1)
		->orderBy('n.created','DESC')
		->range(0, $number)
		->addTag('node_access')
		->execute();
	$node_title_list = node_title_list($result);

	return $node_title_list;
}
/**
 * Implements hook_user_view().
 */

function blogsummary_user_view($account){
	$node_title_list = blogsummary_get_posts();
	if(user_access('create blog content', $account)){
		$account->content['blogsummary'] = array(
			'#type'=>'item',
			'#title'=>t('Blog Summary'),
			'#markup' => theme('item_list',array('items' => $node_title_list['#items'])),
		);
	}
}
