<?php

/**
 * Implements hook_menu()
 */

function blogsummary_menu(){
	$items['user/%user/blog'] = array(
		'title' => 'Posts',
		'page callback' => 'blogsummary_get_posts',
		'access callback' => TRUE,
		'type' => MENU_LOCAL_TASK,
		'weight' => 0,
	);
	return $items;
}

/**
 * Get the Recent 5 Posts 
 *
 * @param: $number
 * 		An optional number which specify the number of posts to show on the dashboard page
 * @return
 *      A renderable array containing the posts
 */
function blogsummary_get_posts($number = 5){
	$query = db_select('node','n');
	$u_alias = $query->innerJoin('users','u','%alias.uid=n.uid');
	$query->addField($u_alias, 'name', 'username');
	$result = $query
		->fields('n',array('nid', 'title','created'))
		->condition("{$u_alias}.name", 'dustsnow')
		->condition('type', 'blog')
		->condition('n.status', 1)
		->orderBy('n.created','DESC')
		->range(0, $number)
		->addTag('node_access')
		->execute();
	$node_title_list = node_title_list($result);

	return $node_title_list;
}
/**
 * Implements hook_user_view().
 */

function blogsummary_user_view($account){
	$query = db_select('node','n');
	$u_alias = $query->innerJoin('users','u','%alias.uid=n.uid');
	$query->addField($u_alias, 'name', 'username');
	$result = $query
		->fields('n',array('nid', 'title','created'))
		->condition("{$u_alias}.name", 'dustsnow')
		->condition('type', 'blog')
		->condition('n.status', 1)
		->orderBy('n.created','DESC')
		->range(0, 5)
		->addTag('node_access')
		->execute();
	$node_title_list = node_title_list($result);
	if(user_access('create blog content', $account)){
		$account->content['blogsummary'] = array(
			'#type'=>'item',
			'#title'=>t('Blog Summary'),
			'#markup' => theme('item_list',array('items' => $node_title_list['#items'])),
		);
	}
}
